### ISSUE TITLE
Adding markdown prettier formatter

### ISSUE THREAD

**Issue by talzid** [thoth-tech/documentation#5]
We have set up a new repo as per request of Andrew: all documentation being stored together in one single location.
This is a product of @sksingh2022 's showcase on the 8/4/22.

As all documentation will be written in markdown, @tancnle could you please set up the formatter workflow. I have copied some of the files across from handbook (and renamed it to documentation in the code). However, I have absolutely no idea how to set up the workflow - I am willing to learn with some guidance.

There is no rush on this

**Comment by tancnle** [comment]
@talzid we can copy the workflow file `https://github.com/thoth-tech/handbook/blob/main/.github/workflows/ci.yml` and place it in the same directory structure to have the pipeline setup.

**Comment by talzid** [comment]
I will give it a go

**Comment by talzid** [comment]
#8 seems like its working 
as in the check is running on its own pr
